Club.create(name: 'Pivotal Denver', country: 'USA')
Club.create(name: 'Pivotal Labs Chicago', country: 'USA')
Club.create(name: 'Friend Sharing', country: 'USA')
Club.create(name: 'Pivotal - Toronto', country: 'USA')
Club.create(name: 'Zendesk', country: 'USA')
Club.create(name: 'Unitt', country: 'USA')
Club.create(name: 'Philosophie LA', country: 'USA')
Club.create(name: 'InfluxDB San Francisco', country: 'USA')
Club.create(name: 'Airtasker', country: 'USA')
Club.create(name: 'Planning Center Online', country: 'USA')
Club.create(name: 'My New Club', country: 'USA')
Club.create(name: 'Guvera', country: 'USA')
Club.create(name: 'Tactile', country: 'USA')
Club.create(name: 'Pivotal London', country: 'USA')
Club.create(name: 'CARS', country: 'USA')
Club.create(name: 'Uber', country: 'USA')
Club.create(name: 'Beginners ping pong', country: 'USA')
Club.create(name: 'Pivotal Labs Santa Monica', country: 'USA')
Club.create(name: 'Pivotal Labs NYC', country: 'USA')
Club.create(name: 'Spokeo', country: 'USA')
Club.create(name: 'x.ai', country: 'USA')
Club.create(name: 'Splash', country: 'USA')
Club.create(name: 'Hooroo', country: 'USA')
Club.create(name: 'DiUS', country: 'USA')
Club.create(name: 'MovableInk', country: 'USA')
Club.create(name: 'Deloitte Digital Denver', country: 'USA')
Club.create(name: 'Case Commons', country: 'USA')
Club.create(name: 'Joynture', country: 'USA')
Club.create(name: 'Southland', country: 'USA')
Club.create(name: 'Favorite Medium', country: 'USA')
Club.create(name: 'Tester', country: 'USA')
Club.create(name: 'ShopKeep', country: 'USA')
Club.create(name: 'Trucker.io', country: 'USA')
Club.create(name: 'we', country: 'USA')
Club.create(name: 'Kitchensurfing', country: 'USA')
Club.create(name: 'Hightower', country: 'USA')
Club.create(name: 'gSchool Denver', country: 'USA')
Club.create(name: 'NerdWallet', country: 'USA')
Club.create(name: 'Wondersauce', country: 'USA')
Club.create(name: 'Blueprint Health', country: 'USA')
Club.create(name: 'DiUS Sydney', country: 'USA')
Club.create(name: 'LiveAction', country: 'USA')
Club.create(name: 'Shoes of Prey', country: 'USA')
Club.create(name: 'Antistatique', country: 'USA')
Club.create(name: 'Chartboost', country: 'USA')
Club.create(name: 'Unpakt', country: 'USA')
Club.create(name: 'Medium', country: 'USA')
Club.create(name: 'Squarespace', country: 'USA')
Club.create(name: 'Abstraktion', country: 'USA')
Club.create(name: 'AlphaSights NY', country: 'USA')
Club.create(name: 'CardFlight', country: 'USA')
Club.create(name: 'livea', country: 'USA')
Club.create(name: 'Samba', country: 'USA')
Club.create(name: 'VonChurch', country: 'USA')
Club.create(name: 'Perpetual', country: 'USA')
Club.create(name: 'Click PR', country: 'USA')
Club.create(name: 'Business Insider', country: 'USA')
Club.create(name: 'ISIS', country: 'USA')
Club.create(name: 'Ramendons', country: 'USA')
Club.create(name: 'Customer.io', country: 'USA')
Club.create(name: 'Bigcommerce', country: 'USA')
Club.create(name: 'Paws for Life', country: 'USA')
Club.create(name: 'SassConf', country: 'USA')
Club.create(name: 'Rap Genius', country: 'USA')
Club.create(name: 'Inspire9', country: 'USA')
Club.create(name: 'XO Group', country: 'USA')
Club.create(name: 'Olin College', country: 'USA')
Club.create(name: 'WeWork FiDi', country: 'USA')
Club.create(name: 'MYOB', country: 'USA')
Club.create(name: 'McCann Sydney', country: 'USA')
Club.create(name: 'AngelCube', country: 'USA')
Club.create(name: 'Brewster', country: 'USA')
Club.create(name: 'CareMonkey', country: 'USA')
Club.create(name: 'Attendly', country: 'USA')
Club.create(name: 'Addepar', country: 'USA')
Club.create(name: 'Pivotal Labs SF', country: 'USA')
Club.create(name: 'Cogent', country: 'USA')
Club.create(name: 'Redbubble', country: 'USA')
Club.create(name: 'Artsy', country: 'USA')
Club.create(name: 'Foobar', country: 'USA')
Club.create(name: 'Projective Space L.E.S.', country: 'USA')
Club.create(name: 'GUST NYC', country: 'USA')
Club.create(name: 'Etsy', country: 'USA')
Club.create(name: 'Techstars NYC Spring 2013', country: 'USA')
Club.create(name: 'Haven Agency', country: 'USA')
Club.create(name: 'The Royals', country: 'USA')
Club.create(name: 'Sensis', country: 'USA')
Club.create(name: 'Amplify NY', country: 'USA')
Club.create(name: 'Sailthru', country: 'USA')
Club.create(name: 'Meetup', country: 'USA')
Club.create(name: 'R/GA London', country: 'USA')
Club.create(name: 'Sugar Hill - Tryall', country: 'USA')
Club.create(name: 'ChallengePost', country: 'USA')
Club.create(name: 'Sidetour', country: 'USA')
Club.create(name: 'Monetate', country: 'USA')
Club.create(name: 'C3 NYC', country: 'USA')
