Club.create(name: 'Pivotal Denver', city: 'Denver', state: 'CO', country: 'US')
Club.create(name: 'Pivotal Labs Chicago', city: 'Chicago', state: 'IL', country: 'US')
Club.create(name: 'Friend Sharing', country: 'US')
Club.create(name: 'Pivotal - Toronto', city: 'Toronto', country: 'CA')
Club.create(name: 'Zendesk', city: 'San Francisco', state: 'CA', country: 'US')
Club.create(name: 'Unitt', country: 'US')
Club.create(name: 'Philosophie LA', city: 'Los Angeles', state: 'CA', country: 'US')
Club.create(name: 'InfluxDB San Francisco', city: 'San Francisco', state: 'CA', country: 'US')
Club.create(name: 'Airtasker', country: 'US')
Club.create(name: 'Planning Center Online', country: 'US')
Club.create(name: 'My New Club', country: 'US')
Club.create(name: 'Guvera', city: 'Robina', state: 'QLD', country: 'AU') # queensland, australia
Club.create(name: 'Tactile', city: 'Redwood City', state: 'CA', country: 'US')
Club.create(name: 'Pivotal London', city: 'London', state: 'London', country: 'UK')
Club.create(name: 'CARS', country: 'US')
Club.create(name: 'Uber', country: 'US')
Club.create(name: 'Beginners ping pong', country: 'US')
Club.create(name: 'Pivotal Labs Santa Monica', state: 'CA', city: 'Santa Monica', country: 'US')
Club.create(name: 'Pivotal Labs NYC', city: 'New York', state: 'NY', country: 'US')
Club.create(name: 'Spokeo', city: 'Pasadena', state: 'CA', country: 'US')
Club.create(name: 'x.ai', city: 'New York', state: 'NY', country: 'US')
Club.create(name: 'Splash', country: 'US')
Club.create(name: 'Hooroo', country: 'AU')
Club.create(name: 'DiUS', city: 'Sydney', state: 'NSW', country: 'AU')
Club.create(name: 'MovableInk', city: 'New York', state: 'NY', country: 'US')
Club.create(name: 'Deloitte Digital Denver', city: 'Denver', state: 'CO', country: 'US')
Club.create(name: 'Case Commons', city: 'New York', state: 'NY', country: 'US')
Club.create(name: 'Joynture', city: 'New York', state: 'NY', country: 'US')
Club.create(name: 'Southland', country: 'US')
Club.create(name: 'Favorite Medium', city: 'San Francisco', state: 'CA', country: 'US')
Club.create(name: 'Tester', country: 'UK')
Club.create(name: 'ShopKeep', city: 'New York', state: 'NY', country: 'US')
Club.create(name: 'Trucker.io', country: 'US')
Club.create(name: 'we', country: 'US')
Club.create(name: 'Kitchensurfing', city: 'New York', state: 'NY', country: 'US')
Club.create(name: 'Hightower', city: 'Englewood', state: 'CO', country: 'US')
Club.create(name: 'gSchool Denver', city: 'Denver', state: 'CO', country: 'US')
Club.create(name: 'NerdWallet', city: 'San Francisco', state: 'CA', country: 'US')
Club.create(name: 'Wondersauce', city: 'New York', state: 'NY', country: 'US')
Club.create(name: 'Blueprint Health', city: 'New York', state: 'NY', country: 'US')
Club.create(name: 'DiUS Sydney', city: 'Sydney', state: 'NSW', country: 'AU')
Club.create(name: 'LiveAction', country: 'US')
Club.create(name: 'Shoes of Prey', city: 'Sydney', state: 'NSW', country: 'AU')
Club.create(name: 'Antistatique', city: 'Geneva', country: 'CH') # switzerland
Club.create(name: 'Chartboost', city: 'San Francisco', state: 'CA', country: 'US')
Club.create(name: 'Unpakt', city: 'New York', state: 'CA', country: 'US')
Club.create(name: 'Medium', city: 'San Francisco', state: 'CA', country: 'US')
Club.create(name: 'Squarespace', city: 'New York', state: 'NY', country: 'US')
Club.create(name: 'Abstraktion', country: 'US')
Club.create(name: 'AlphaSights NY', city: 'New York', state: 'NY', country: 'US')
Club.create(name: 'CardFlight', city: 'New York', state: 'NY', country: 'US')
Club.create(name: 'livea', country: 'US')
Club.create(name: 'Samba', country: 'US')
Club.create(name: 'VonChurch', country: 'US')
Club.create(name: 'Perpetual', country: 'US')
Club.create(name: 'Click PR', country: 'US')
Club.create(name: 'Business Insider', country: 'US')
Club.create(name: 'ISIS', country: 'US')
Club.create(name: 'Ramendons', country: 'US')
Club.create(name: 'Customer.io', country: 'US')
Club.create(name: 'Bigcommerce', country: 'US')
Club.create(name: 'Paws for Life', country: 'US')
Club.create(name: 'SassConf', country: 'US')
Club.create(name: 'Rap Genius', country: 'US')
Club.create(name: 'Inspire9', country: 'US')
Club.create(name: 'XO Group', country: 'US')
Club.create(name: 'Olin College', country: 'US')
Club.create(name: 'WeWork FiDi', country: 'US')
Club.create(name: 'MYOB', country: 'US')
Club.create(name: 'McCann Sydney', country: 'US')
Club.create(name: 'AngelCube', country: 'US')
Club.create(name: 'Brewster', country: 'US')
Club.create(name: 'CareMonkey', country: 'US')
Club.create(name: 'Attendly', country: 'US')
Club.create(name: 'Addepar', country: 'US')
Club.create(name: 'Pivotal Labs SF', country: 'US')
Club.create(name: 'Cogent', country: 'US')
Club.create(name: 'Redbubble', country: 'US')
Club.create(name: 'Artsy', country: 'US')
Club.create(name: 'Foobar', country: 'US')
Club.create(name: 'Projective Space L.E.S.', country: 'US')
Club.create(name: 'GUST NYC', country: 'US')
Club.create(name: 'Etsy', country: 'US')
Club.create(name: 'Techstars NYC Spring 2013', country: 'US')
Club.create(name: 'Haven Agency', country: 'US')
Club.create(name: 'The Royals', country: 'US')
Club.create(name: 'Sensis', country: 'US')
Club.create(name: 'Amplify NY', country: 'US')
Club.create(name: 'Sailthru', country: 'US')
Club.create(name: 'Meetup', country: 'US')
Club.create(name: 'R/GA London', country: 'UK')
Club.create(name: 'Sugar Hill - Tryall', country: 'US')
Club.create(name: 'ChallengePost', country: 'US')
Club.create(name: 'Sidetour', country: 'US')
Club.create(name: 'Monetate', country: 'US')
Club.create(name: 'C3 NYC', country: 'US')
